import type { CountrySettings } from "@/lib/valuation/types";

export const defaultCountries: CountrySettings[] = [
  {
    id: "us",
    name: "United States",
    currency: "USD",
    riskFreeRate: 0.042,
    riskFreeCurve: "long",
    equityRiskPremium: 0.055,
    inflation: 0.027,
    taxRate: 0.25,
    countryRiskPremium: 0,
    sovereignSpread: 0,
    defaultSpreads: [
      { rating: "AAA", spread: 0.007 },
      { rating: "AA", spread: 0.012 },
      { rating: "A", spread: 0.018 },
      { rating: "BBB", spread: 0.028 },
      { rating: "BB", spread: 0.045 },
      { rating: "B", spread: 0.065 },
      { rating: "CCC", spread: 0.095 },
    ],
  },
  {
    id: "italy",
    name: "Italy",
    currency: "EUR",
    riskFreeRate: 0.032,
    riskFreeCurve: "long",
    equityRiskPremium: 0.062,
    inflation: 0.024,
    taxRate: 0.28,
    countryRiskPremium: 0.012,
    sovereignSpread: 0.01,
    defaultSpreads: [
      { rating: "AAA", spread: 0.01 },
      { rating: "AA", spread: 0.016 },
      { rating: "A", spread: 0.022 },
      { rating: "BBB", spread: 0.035 },
      { rating: "BB", spread: 0.052 },
      { rating: "B", spread: 0.072 },
      { rating: "CCC", spread: 0.1 },
    ],
  },
  {
    id: "germany",
    name: "Germany",
    currency: "EUR",
    riskFreeRate: 0.028,
    riskFreeCurve: "long",
    equityRiskPremium: 0.052,
    inflation: 0.022,
    taxRate: 0.27,
    countryRiskPremium: 0,
    sovereignSpread: 0,
    defaultSpreads: [
      { rating: "AAA", spread: 0.006 },
      { rating: "AA", spread: 0.011 },
      { rating: "A", spread: 0.017 },
      { rating: "BBB", spread: 0.026 },
      { rating: "BB", spread: 0.041 },
      { rating: "B", spread: 0.058 },
      { rating: "CCC", spread: 0.09 },
    ],
  },
  {
    id: "uk",
    name: "United Kingdom",
    currency: "GBP",
    riskFreeRate: 0.038,
    riskFreeCurve: "long",
    equityRiskPremium: 0.057,
    inflation: 0.026,
    taxRate: 0.25,
    countryRiskPremium: 0.005,
    sovereignSpread: 0.004,
    defaultSpreads: [
      { rating: "AAA", spread: 0.008 },
      { rating: "AA", spread: 0.013 },
      { rating: "A", spread: 0.019 },
      { rating: "BBB", spread: 0.03 },
      { rating: "BB", spread: 0.047 },
      { rating: "B", spread: 0.066 },
      { rating: "CCC", spread: 0.096 },
    ],
  },
  {
    id: "india",
    name: "India",
    currency: "INR",
    riskFreeRate: 0.071,
    riskFreeCurve: "long",
    equityRiskPremium: 0.068,
    inflation: 0.051,
    taxRate: 0.25,
    countryRiskPremium: 0.02,
    sovereignSpread: 0.018,
    defaultSpreads: [
      { rating: "AAA", spread: 0.018 },
      { rating: "AA", spread: 0.025 },
      { rating: "A", spread: 0.032 },
      { rating: "BBB", spread: 0.045 },
      { rating: "BB", spread: 0.06 },
      { rating: "B", spread: 0.078 },
      { rating: "CCC", spread: 0.11 },
    ],
  },
  {
    id: "custom",
    name: "Custom",
    currency: "USD",
    riskFreeRate: 0.04,
    riskFreeCurve: "long",
    equityRiskPremium: 0.055,
    inflation: 0.02,
    taxRate: 0.25,
    countryRiskPremium: 0,
    sovereignSpread: 0,
    defaultSpreads: [
      { rating: "AAA", spread: 0.01 },
      { rating: "AA", spread: 0.015 },
      { rating: "A", spread: 0.02 },
      { rating: "BBB", spread: 0.03 },
      { rating: "BB", spread: 0.05 },
      { rating: "B", spread: 0.07 },
      { rating: "CCC", spread: 0.1 },
    ],
  },
];
